---
- name: calculate rhel version to install ius repository
  set_fact:
    rhel_version: "{{ '7' if ansible_distribution == 'Amazon' and ansible_service_mgr == 'sysvinit' or ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7' else '6' }}"

- name: install ius repository
  yum:
    name: https://rhel{{ rhel_version }}.iuscommunity.org/ius-release.rpm
